// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzviopkcdfzrexqhwrwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dmlvcGtjZGZ6cmV4cWh3cndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzUyOTIsImV4cCI6MjA3MTkxMTI5Mn0.mW5dnZxpsj6BxLaiDtkpUl2wa8-8Ye4lX2ruqvj7JLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});